# Generated by Django 4.1.3 on 2022-11-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='', max_length=100)),
                ('store_image', models.TextField(default='', max_length=256)),
                ('store_rating', models.CharField(default='', max_length=100)),
                ('store_category', models.CharField(default='', max_length=100)),
                ('store_address', models.CharField(default='', max_length=256)),
                ('store_view', models.CharField(default='', max_length=100)),
                ('store_review', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'restaurant',
            },
        ),
    ]
